__int64 __fastcall VBoxGuest_RTLogCreateEx(
        unsigned __int64 a1,
        int a2,
        _BYTE *a3,
        __int64 a4,
        unsigned int a5,
        __int64 a6,
        double a7,
        double a8,
        double a9,
        double a10,
        double a11,
        double a12,
        double a13,
        double a14,
        int a15,
        int a16,
        __int64 a17,
        unsigned int a18,
        __int64 a19,
        int a20,
        __int64 a21)
{
  return VBoxGuest_RTLogCreateExV(
           a1,
           a2,
           a3,
           a7,
           a8,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a4,
           a5,
           a6,
           a15,
           a16,
           a17,
           a18,
           a19,
           a20,
           a21);
}
